### ISSUE TITLE
Fredrick Ludwig Hoffman

### ISSUE THREAD

**Issue by MilesOtt** [sctyner/history_of_statistics#18]
Former ASA president (1911) and VP of Prudential and author of "Race Traits and Tendencies of the American Negro"

https://archive.org/details/racetraitstenden00hoff/page/n6/mode/2up

https://en.wikipedia.org/wiki/Frederick_Ludwig_Hoffman

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1497788/

Written by his grandson (!) in amstat news blog: https://magazine.amstat.org/blog/2018/10/29/sih-hoffman/

More on Hoffman here: https://www.pbs.org/race/000_About/002_04-background-01-05.htm

**Comment by nicholasjhorton** [comment]
Yipes.

**Comment by sctyner** [comment]
Just heard about him in an interview with Ibram X. Kendi. Kendi's piece: https://amp.theatlantic.com/amp/article/612457/

**Comment by sctyner** [comment]
Reflected in the new statistics for evil page
