### ISSUE TITLE
Statistical Science Conversations

### ISSUE THREAD

**Issue by Scott-Coggeshall** [sctyner/history_of_statistics#6]
The journal *Statistical Science* has an interview series called Conversations that includes interviews with many prominent statisticians from the 20th century. The entire series is open access and can be found here:
https://imstat.org/journals-and-publications/statistical-science/conversations/

Some of the people interviewed include
- Dorothy Gilford
- Charles Stein
- Nan Laird
- David Cox
- C.R. Rao
- David Blackwell
- Bradley Efron

and many many more.

**Comment by kiegan** [comment]
Awesome - added, thank you!
