### ISSUE TITLE
Stigler stuff

### ISSUE THREAD

**Issue by maxbiostat** [sctyner/history_of_statistics#7]
[Steven Stigler](https://en.wikipedia.org/wiki/Stephen_Stigler) has written extensively on the history of Statistics. 
I read [The history of statistics : the measurement of uncertainty before 1900](https://archive.org/details/historyofstatist00stig) and it was enlightening. 
Figures such as Laplace and [Quetelet](https://en.wikipedia.org/wiki/Adolphe_Quetelet) figure prominently. Doesn't take much of a "critical" stance, but is a great read.

After deliberation, I can add some stuff.

**Comment by sctyner** [comment]
Thanks for the links! Added
